import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className="bg-neutral-800">
    <nav className="bg-purple-700 p-4">
      <div className="container mx-auto flex justify-between items-center">
        <h1 className="text-3xl font-bold">CodeWise</h1>
        <ul className="flex space-x-6">
          <li><a href="#" className="text-white hover:text-purple-300">Home</a></li>
          <li><a href="#" className="text-white hover:text-purple-300">Courses</a></li>
          <li><a href="#" className="text-white hover:text-purple-300">Leaderboard</a></li>
          <li><a href="#" className="text-white hover:text-purple-300">Community</a></li>
        </ul>
        <button className="bg-white text-black px-4 py-2 rounded-lg hover:bg-purple-500">Login</button>
      </div>
    </nav>
    {children}
    </body>
    </html>
  );
}
