import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import { FacebookIcon, HouseIcon, MailIcon, PhoneCallIcon } from "lucide-react";
import { InstagramLogoIcon } from "@radix-ui/react-icons";
import { Button } from "@/components/ui/button";
import Navbar from "@/components/Navbar";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html>
			<body className="bg-neutral-800 min-h-screen overflow-x-hidden">
				<Navbar />
				<div className="flex justify-center">{children}</div>

				{/* Stopka */}
				<footer className="bg-neutral-900 text-white pt-2 bottom-0 w-screen">
					<div className="container mx-auto flex flex-col">
						<h2 className="text-xl font-bold mb-4 text-center">
							Kontakt
						</h2>
						<div className="flex justify-around">
							<p className="text-sm hover:text-purple-500 transition hover:scale-125">
								<MailIcon className="mx-auto hover:text-purple-" />{" "}
								support@codewise.com
							</p>
							<p className="text-sm hover:text-purple-500 transition hover:scale-125">
								<PhoneCallIcon className="mx-auto" /> +48 123
								456 789
							</p>
							<p className="text-sm hover:text-purple-500 transition hover:scale-125">
								<HouseIcon className="mx-auto" /> Warszawa,
								Polska
							</p>
							<p className="text-sm hover:text-purple-500 transition hover:scale-125">
								<FacebookIcon className="mx-auto" /> CodeWise
							</p>
							<p className="text-sm hover:text-purple-500 transition hover:scale-125">
								<InstagramLogoIcon className="mx-auto scale-125" />{" "}
								CodeWise
							</p>
						</div>
					</div>
					<div className="mt-8 text-center text-sm border-t border-neutral-700 pt-4">
						<p>
							&copy; {new Date().getFullYear()} CodeWise. Wszelkie
							prawa zastrzeżone.
						</p>
					</div>
				</footer>
			</body>
		</html>
	);
}
